library(dplyr)
library(Rcpp)
library(readxl)
library(stringr)
library(gcookbook)
library(gridExtra)
library(ggpubr)
library(tibble)
library(R.utils)

setwd("/home/huanhuan/project/eQTL_Catalogue/script/hotspot_associate_study_and_resource/output/")
org <- read.csv("02_adjust_tissue_need_study_for_hotspot_annotation_cistromeDB_refine.tsv",header = T,sep = "\t") %>% as.data.frame()
anno <- read.csv("03_hotspots_tissue_type_annotation_roadmap_cistromeDB_refine.tsv",header = T,sep = "\t") %>% as.data.frame()
anno$Marker <-gsub("Human_CHROMATIN_Accessibility","CHROMATIN_Accessibility",anno$Marker )
anno$Marker <-gsub("Human_FACTOR","TFBS",anno$Marker )
anno1 <-reshape2::dcast(anno,study+qtl_group ~ Marker)
fdat <- left_join(org,anno1,by=c("study","qtl_group"))
fdat <-fdat%>%dplyr::select(-HISTONE_MARK_AND_VARIANT)
write.table(fdat,"04_merge_hotspot_and_annotation_info.tsv",row.names = F, col.names = T,quote =F,sep="\t")
