perl 02_Completion_snp_for_PancanQTL_by_1kg.pl
perl 02_filter_sig_egene.pl #
Rscript 03_NHP_big_par.R
perl 04_filter_hotspot_for_interval18_eQTL.pl
Rscript 05_barplot_hotspot_length_distribution_ori.R
Rscript 05_plot_distribution_the_length_of_hotspot_ori.R
